/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ret.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

s *
mod_s_1(argp, clnt)
	s *argp;
	CLIENT *clnt;
{
	static s clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, MOD_S, xdr_s, argp, xdr_s, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
