/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ret.h"

bool_t
xdr_s(xdrs, objp)
	XDR *xdrs;
	s *objp;
{

	if (!xdr_int(xdrs, &objp->value))
		return (FALSE);
	return (TRUE);
}
